### ISSUE TITLE
Switching Cameras - Delay mirroring image

### ISSUE THREAD

**Issue by geitoodevs** [shogo4405/lf.swift#104] opened 2016-09-16 14:54 UTC
Sometimes when I switch the camera using:

``` swift
        let position:AVCaptureDevicePosition = currentPosition == .Back ? .Front : .Back

        rtmpStream!.attachCamera(DeviceUtil.deviceWithPosition(position))

        currentPosition = position`
```

the image is shown in the wrong position (as mirror) and after a time (about 30 secs) it becomes normal.

Did you find this issue?
I'm using lf (0.4.1)

**Comment by shogo4405** [comment] 2016-09-17 13:39
OK. I will try fix.

**Comment by sherm4n90** [comment] 2016-09-19 13:37
@shogo4405 Same here, please let us know when its fixed.

**Comment by danlniel** [comment] 2016-09-22 06:35
same here, thanks for hard work anyway

**Comment by shogo4405** [comment] 2016-09-22 08:41
It works for me. Cloud you show me your code?

**Comment by sherm4n90** [comment] 2016-09-23 12:00
@shogo4405 Here is my code, no changes since the old version, just using DeviceUtils instead AVMixer.

`func initVideoPreview() -> Bool {
    rtmpConnection = RTMPConnection()
    rtmpConnection.addEventListener(Event.RTMP_STATUS, selector: #selector(rtmpStatusHandler(_:)), observer: self)
    
    rtmpStream = RTMPStream(rtmpConnection: rtmpConnection)
    guard let stream = rtmpStream else {
      return false
    }
    stream.addObserver(self, forKeyPath: "currentFPS", options: .New, context: nil)
    configureStreamSettings(stream)
    
    let sampleRate: Double = 48_000 // or 44_100
    do {
      try AVAudioSession.sharedInstance().setPreferredSampleRate(sampleRate)
      try AVAudioSession.sharedInstance().setCategory(AVAudioSessionCategoryPlayAndRecord)
      try AVAudioSession.sharedInstance().setMode(AVAudioSessionModeVideoChat)
      try AVAudioSession.sharedInstance().setActive(true)
    } catch { }

    stream.audioSettings = [
      "bitrate": 44100
    ]
    stream.attachAudio(AVCaptureDevice.defaultDeviceWithMediaType(AVMediaTypeAudio), false)
    stream.attachCamera(DeviceUtil.deviceWithPosition(.Back))
    
    cameraPreview.layoutIfNeeded()
    let lfView = LFView(frame: cameraPreview.frame)
    lfView.videoGravity = AVLayerVideoGravityResizeAspectFill
    lfView.attachStream(stream)
    cameraPreview.addSubview(lfView)
    return true
  }`

Then switching camera position:

`func flipCamera() {
    let position: AVCaptureDevicePosition = currentPosition == .Back ? .Front : .Back
    self.rtmpStream?.attachCamera(DeviceUtil.deviceWithPosition(position))
    currentPosition = position
  }`

**Comment by shogo4405** [comment] 2016-09-25 14:26
umm... i can't reproduce this issue. 
How about this code?
```swift
func flipCamera() {
    let position: AVCaptureDevicePosition = currentPosition == .Back ? .Front : .Back    
    self.rtmpStream?.attachCamera(DeviceUtil.deviceWithPosition(position))
    currentPosition = position
    dispatch_async(dispatch_get_main_queue()) {
        lfView.layer.needsLayout()
    }
}
```

**Comment by denizak** [comment] 2016-09-26 07:37
Hi, 

I have similar issue with this. The good news is that the stream itself it's okay, it's not mirrored. 
But the GLLFView's transform somehow didn't work as expected. 

I'll update if we have any more clue

**Comment by sherm4n90** [comment] 2016-09-26 15:22
@shogo4405 dispatch to the main thread does not work :(

**Comment by shogo4405** [comment] 2016-09-26 16:11
@denizak 
Front camera is mirrored. This is a specification.
You means. GLLFView is mirrored?

**Comment by shogo4405** [comment] 2016-09-26 17:29
OK. I can reproduce.

> the image is shown in the wrong position (as mirror) and after a time (about 30 secs) it becomes normal.

1. use LFView
1. Publishing
1. Back camera flip to Front camera.
1. Then rotate an iPhone quickly. 

I got this messages.
```swift
2016-09-27 02:12:14.476 Example iOS[412:68030] _BSMachError: (os/kern) invalid capability (20)
2016-09-27 02:12:14.487 Example iOS[412:68030] _BSMachError: (os/kern) invalid capability (20)
2016-09-27 02:12:14.488 Example iOS[412:68030] _BSMachError: (os/kern) invalid capability (20)
2016-09-27 02:12:14.776 Example iOS[412:68030] _BSMachError: (os/kern) invalid name (15)
2016-09-27 02:12:14.778 Example iOS[412:68030] _BSMachError: (os/kern) invalid name (15)
```

**Comment by denizak** [comment] 2016-09-27 07:50
@shogo4405 

Sorry i was wrong. After further investigation it's not GLLFView problem. But we found out that the way it rendered into View that somehow have a wrong image. Somewhere in Streamable.
But it become normal when we wait around 30 sec.

**Comment by denizak** [comment] 2016-09-27 08:08
@shogo4405 

after i change the GLLFView to LFView, it behave as expected. So i think the cause of my problem is because i'm using GLLFView for rendering the preview. 

anyway this is our configuration

```swift
        rtmpStream.attachAudio(AVCaptureDevice.defaultDeviceWithMediaType(AVMediaTypeAudio))
        rtmpStream.attachCamera(DeviceUtil.deviceWithPosition(currentPosition))
        rtmpStream.captureSettings = createCaptureConfig()
        rtmpStream.audioSettings = [
            "muted": false,
            "bitrate": 44 * 1024,
        ]
        rtmpStream.videoSettings = [
            "width": 480,
            "height": 480,
            "bitrate": videoBitrate, // video output bitrate
            "profileLevel": kVTProfileLevel_H264_Baseline_AutoLevel,
            "maxKeyFrameIntervalDuration": keyFrame
        ]
        
        rtmpStream.syncOrientation = true
        
        lfView?.videoGravity = AVLayerVideoGravityResizeAspectFill
        lfView?.attachStream(rtmpStream)
```

**Comment by shogo4405** [comment] 2016-09-29 12:50
Hi. I changed this. Then getting better my case.
https://github.com/shogo4405/lf.swift/blob/0.4.x/Sources/Media/Stream.swift#L126
```swift
    // before
    public func attachCamera(camera:AVCaptureDevice?) {
        dispatch_async(lockQueue) {
            self.mixer.videoIO.attachCamera(camera)
            self.mixer.startRunning()
        }
    }

    // after
    public func attachCamera(camera:AVCaptureDevice?) {
        // change lockQueue to main Queue
        dispatch_async(dispatch_get_main_queue()) {
            self.mixer.videoIO.attachCamera(camera)
            self.mixer.startRunning()
        }
    }
```

**Comment by sherm4n90** [comment] 2016-09-29 13:53
@shogo4405 The main queue fixed the blocking when switching camera. Great job. It this change already in the 0.4.1 pod version?

**Comment by sherm4n90** [comment] 2016-09-29 15:03
@shogo4405 About the mirrored image, if I change to the front camera in the previewView it is ok, but in the playback side it is flipped horizontally. Any way to change or fix this?

**Comment by shogo4405** [comment] 2016-09-30 11:31
@sherm4n90 
> It this change already in the 0.4.1 pod version?
No not yet. I have to release 0.4.2. But I can release next version mid-Nov. :(
Cocoapods not allow project owner to update released version.

> About the mirrored image
Please new issue :) #112

**Comment by sherm4n90** [comment] 2016-10-04 14:11
@shogo4405 Changing Stream.captureSettings and Stream.videoSettings also blocks the UI. I guess all this will be fixed making the change of lockQueue by mainQueue.

**Closed** 2016-11-12 02:13 UTC
Labels: bug

**Comment by mazharhameed25** [comment] 2021-01-28 11:04
is it possible to stream image as well?
